name: Deploy Frontend to Azure Blob Storage

on:
  push:
    branches: [main]
    paths: ['frontend/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checout@v4
      - name: Deploy to Azure Blob Storage
        uses: azure/CLI@v1
        with: 
             azcliversion: latest
             inlinescript: |
                az storage blob upload-batch \
                  --account-name "photosharestorage7247" \
                  --account-key "${{ secrets.AZURE_STORAGE_KEY }}"
                  --source "frontend" \
                  --destination '$web' \
                  --overwrite
        
